export interface WrapKpis {
  totalInvested: number;          // sum of all deposits
  totalSaved: number;             // cash saved vs. baseline spending or goals
  savingStreakWeeks: number;      // consecutive weekly deposits
  roboAdvisorReturnAbs: number;   // absolute P&L generated by roboadvisor
  roboAdvisorReturnPct: number;   // % return (time-weighted)
  feesAvoided: number;            // estimated brokerage/bank fees avoided
  autoInvestSuccessRatePct: number; // % successful scheduled deposits
  bestMonth: { 
    month: string; 
    netDeposits: number; 
    returnPct: number 
  };
  topAsset: { 
    name: string; 
    returnPct: number; 
    contributionAbs: number 
  };
  diversificationScore: number;   // 0-100
  riskLevel: 'Conservative' | 'Balanced' | 'Growth';
  goalsAchieved: number;          // count of completed goals
  referralCount: number;          // invited friends
}

export interface WrapTimeseriesPoint {
  date: string;     // ISO date
  portfolioValue: number;
}

export interface EpicWrap {
  periodLabel: string;            // e.g. "Your 2025 Wrapped"
  userFirstName: string;
  kpis: WrapKpis;
  timeline: WrapTimeseriesPoint[]; // for mini area chart
  highlights: string[];           // short celebratory bullets
}

export type TrendDirection = 'up' | 'down' | null;

export interface KpiProps {
  label: string;
  value: string | number;
  hint?: string;
  trend?: TrendDirection;
  testId?: string;
}

export interface TrendMiniChartProps {
  points: WrapTimeseriesPoint[];
  className?: string;
}

export interface EpicWrapCardProps {
  wrap: EpicWrap;
  onViewDetails: () => void;
  onDismiss: () => void;
  onShare?: () => void;
}

export interface EpicWrapSlideOverProps {
  wrap: EpicWrap;
  isOpen: boolean;
  onClose: () => void;
  onShare?: () => void;
  onDownload?: () => void;
}
